import { GoogleGenAI, Type } from "@google/genai";
import { AIService, BrandPrompt } from "../types";

export class GeminiProvider implements AIService {
  private ai: GoogleGenAI;

  constructor(apiKey: string) {
    this.ai = new GoogleGenAI({ apiKey });
  }

  getName() {
    return "Gemini";
  }

  async generatePrompts(productDescription: string): Promise<BrandPrompt[]> {
    const response = await this.ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `You are a creative director. Given a product description, generate 3 distinct image generation prompts for different mediums: a Billboard, a Newspaper advertisement, and a Social Media post.
      
      Product: ${productDescription}
      
      Constraints:
      - MAINTAIN PRODUCT CONSISTENCY: The product should look identical in all three shots.
      - NO PEOPLE: There should be absolutely no humans in any of the images.
      - MEDIUM SPECIFIC: 
          - Billboard: High impact, wide shot, urban or scenic background.
          - Newspaper: High contrast, clean layout, perhaps slightly more text-focused or classic feel.
          - Social Post: Trendy, close-up or lifestyle (without people), vibrant colors.
      
      Return the result as a JSON array of objects with 'medium' and 'prompt' fields.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              medium: { type: Type.STRING },
              prompt: { type: Type.STRING },
            },
            required: ["medium", "prompt"],
          },
        },
      },
    });

    return JSON.parse(response.text);
  }

  async generateImage(prompt: string): Promise<string> {
    const response = await this.ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: prompt + " Ensure there are no people in the image. High quality, professional photography.",
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by Gemini");
  }
}
